name: Auto-merge when label approved is added

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Merge the pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            const { data: prData } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            if (prData.mergeable) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log(`✅ PR #${pr.number} merged.`);
            } else {
              console.log(`⚠️ PR #${pr.number} is not mergeable.`);
            }
